{{- if .Values.pdb.enabled }}
apiVersion: policy/v1{{ if semverCompare "<1.21.0" .Capabilities.KubeVersion.Version }}beta1{{ end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "azd-kubernetes-manager.fullname" . }}{{ if semverCompare "<1.21.0" .Capabilities.KubeVersion.Version }}-v1beta1{{ end }}
  labels:
    {{- include "azd-kubernetes-manager.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "azd-kubernetes-manager.selector" . | nindent 6 }}
{{- end }}
