{
 "title": "AZD Kubernetes Manager",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "The duration of Service Hook requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(azd_kubernetes_manager_service_hook_duration_seconds_bucket{name=\"azd-kubernetes-manager\"}[10m])) by (pod, eventType)",
     "legendFormat": "{{pod}} - Event {{eventType}}"
    }
   ]
  },
  {
   "title": "Total number of Service Hooks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(azd_kubernetes_manager_service_hook_count{name=\"azd-kubernetes-manager\"}[1m])) by (pod, eventType)",
     "legendFormat": "{{pod}} - Event {{eventType}}"
    }
   ]
  },
  {
   "title": "Number of Service Hook errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(azd_kubernetes_manager_service_hook_error_count{name=\"azd-kubernetes-manager\"}) by (pod, eventType, reason)",
     "legendFormat": "{{pod}} - Event {{eventType}} {{reason}}"
    }
   ]
  },
  {
   "title": "The total number of liveness probes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(azd_kubernetes_manager_liveness_probe_count{name=\"azd-kubernetes-manager\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Counts of Azure Devops calls returning HTTP 429 (Too Many Requests)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(azd_kubernetes_manager_azd_call_429_count{name=\"azd-kubernetes-manager\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Default Go Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Allocated",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_alloc_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of heap bytes that are in use",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_heap_inuse_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of heap bytes allocated and still in use",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_heap_alloc_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of heap bytes released to OS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_heap_released_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of heap bytes waiting to be used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(go_memstats_heap_idle_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of heap bytes when next garbage collection will take place",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_next_gc_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of heap bytes obtained from system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_heap_sys_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total number of bytes allocated, even if freed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(increase(go_memstats_alloc_bytes_total{name=\"azd-kubernetes-manager\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes used for other system allocations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_other_sys_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes in use by the stack allocator",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_stack_inuse_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes obtained from system for stack allocator",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_stack_sys_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes obtained from system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_sys_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Resident memory size in bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(process_resident_memory_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Virtual memory size in bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(process_virtual_memory_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Default Go Memory Metrics by Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of bytes used by the profiling bucket hash table",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_buck_hash_sys_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes used for garbage collection system metadata",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_gc_sys_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes in use by mcache structures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_mcache_inuse_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes used for mcache structures obtained from system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_mcache_sys_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes in use by mspan structures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_mspan_inuse_bytes{name=\"azd-kubernetes-manager\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Number of bytes used for mspan structures obtained from system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_mspan_sys_bytes{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Default Go Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current number of scrapes being served",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(promhttp_metric_handler_requests_in_flight{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total number of scrapes by HTTP status code",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(increase(promhttp_metric_handler_requests_total{name=\"azd-kubernetes-manager\"}[1m])) by (pod, code)",
       "legendFormat": "{{pod}} - Code {{code}}"
      }
     ]
    },
    {
     "title": "Number of allocated objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_heap_objects{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total user and system CPU time spent in seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(increase(process_cpu_seconds_total{name=\"azd-kubernetes-manager\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC invocation durations quantiles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(go_gc_duration_seconds{name=\"azd-kubernetes-manager\"}) by (quantile)",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "The fraction of this program's available CPU time used by the GC since the program started",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_gc_cpu_fraction{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Go Routines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(go_goroutines{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{Pod}}"
      }
     ]
    },
    {
     "title": "OS Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(go_threads{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total number of pointer lookups",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(increase(go_memstats_lookups_total{name=\"azd-kubernetes-manager\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total number of frees",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(increase(go_memstats_frees_total{name=\"azd-kubernetes-manager\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Maximum number of open file descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(process_max_fds{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total number of mallocs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(increase(go_memstats_mallocs_total{name=\"azd-kubernetes-manager\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of open file descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(process_open_fds{name=\"azd-kubernetes-manager\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}